= Messaging Client Java - Samples for Enterprise Messaging

== Description
SAP Cloud Platform Enterprise Messaging provides a cloud-based messaging framework for the development of decoupled and resilient services and integration flows (using SAP Cloud Integration) to support asynchronous communication principles.
Direct integration with SAP S/4HANA Business Event Handling allows efficient development of innovative and scaling extensions.

This Messaging Client Java Samples project contains a collection of messaging based application to demonstrate the usage of Enterprise Messaging in SAP Cloud Platform. Details to each sample application and the covered scenario are described in next section _List of sample projects_.

For more details of **SAP Cloud Platform Enterprise Messaging** take a look at the link:https://github.com/pages/SAP/enterprise-messaging-samples/[Enterprise Messaging - Messaging Clients landing page] and link:https://help.sap.com/viewer/product/SAP_ENTERPRISE_MESSAGING/Cloud/en-US[SAP Cloud Platform Enterprise Messaging on SAP Help portal].


=== List of sample projects

[cols=3*,options=header]
|===
|Application
|Scenario
|Scenario Description

|link:./emjapi-samples-basic[`emjapi-samples-basic`]
|Basic Messaging Client Java sample for SAP Cloud Platform Enterprise Messaging.
|This sample demonstrates how messages can be send and received from a none SAP CP application. Therefore the messaging sample consists of a `MessageSender` and a `MessageReceiver` (both as a Java class with just a main method).

|link:./emjapi-samples-sapcp[`emjapi-samples-sapcp`]
|Application for Enterprise Messaging based on Spring Web running on SAP Cloud Platform (@ CloudFoundry (with Enterprise Messaging Service)).
|This sample demonstrates how messages can be send and received from a SAP CP deployed application. Therefore the messaging sample provides a _Spring Boot_ based application which provides REST endpoints for _send_ and _receive_ messages via pre-defined queues (see also `manifest.yml`). The REST endpoints are provided via the `MessageController` and the Enterprise Messaging integration in the `MessagingService`.

|link:./emjapi-samples-jms-basic[`emjapi-samples-jms-basic`]
|Basic sample of how to use the Apache Qpid JMS client in combination with the _Messaging Client Java_ to send and receive messages via SAP Cloud Platform Enterprise Messaging.
|This sample demonstrates how messages can be send and received from a none SAP CP application via _JMS_. Therefore the messaging sample consists of a `EmJmsConsumer` and a `EmJmsProducer` which provides the corresponding functionality and an `Application` (which provides a main method to start send/receive samples).

|link:./emjapi-samples-jms-sapcp[`emjapi-samples-jms-sapcp`]
|Application for SAP Cloud Platform Enterprise Messaging via JMS based on Spring Web running on SAP Cloud Platform in the Cloud Foundry environment (with the Enterprise Messaging Service).
|This sample demonstrates how messages can be send and received from a SAP CP deployed application. Therefore the messaging sample provides a _Spring Boot_ based application which provides REST endpoints for _send_ and _receive_ messages via pre-defined queues (see also `manifest.yml`). The REST endpoints are provided via the `MessageController` and the Enterprise Messaging integration as well as the JMS extension in the `MessagingService`.
|===

== Requirements
To run the samples a running `Enterprise Messaging Service @SAP CP` is required. +
For more detailed information and help on how to start with _SAP Cloud Platform Enterprise Messaging_ please check the link:https://help.sap.com/viewer/product/SAP_ENTERPRISE_MESSAGING/Cloud/en-US[SAP help page].

Further necessary configuration and settings are dependent on the specific sample and are documented within each sample project.

== Download and Installation
To download and install the samples just clone this repository via:
```
git clone https://github.com/SAP/enterprise-messaging-client-java-samples
```

For details on how to configure and run the samples please take a look into the README in the corresponding samples directory.

== Support
This project is _'as-is'_ with no support, no changes being made. +
You are welcome to make changes to improve it but we are not available for questions or support of any kind.

== License
Copyright (c) 2018 SAP SE or an SAP affiliate company. All rights reserved. +
This file is licensed under the _SAP SAMPLE CODE LICENSE AGREEMENT, v1.0-071618_ except as noted otherwise in the link:./LICENSE.txt[LICENSE file].