= SAP Enterprise Messaging JMS: SAP CP Application (via JMS)
:toc:

Sample application for SAP Cloud Platform Enterprise Messaging via JMS based on Spring Web running on SAP Cloud Platform in the Cloud Foundry environment (with the Enterprise Messaging Service)).

== Prerequisites

  * Installed _Java 8_ -> link:https://java.com/de/download/[Java download]
  * Installed _Git_ -> link:https://git-scm.com/downloads[Git download]
  * Installed _Maven 3.x_ -> link:https://maven.apache.org/download.cgi[Maven download]
  * A _SAP CP_ Account with `Enterprise Messaging Service` is required. +
    For more detailed information and help on how to start with _SAP Cloud Platform Enterprise Messaging_ please check the link:https://help.sap.com/viewer/product/SAP_ENTERPRISE_MESSAGING/Cloud/en-US[SAP help page].
    ** Optional: Installed _CloudFoundry CLI_ -> link:https://docs.cloudfoundry.org/cf-cli/install-go-cli.html[Installing the cf CLI] 
    *** This must be also fully configured with the corresponding Cloud Foundry landscape to be able to do a `cf push`.
    ** Created Enterprise Messaging Instance (e.g. via cli: `cf cs enterprise-messaging dev emjapi-samples-jms-sapcp -c '{"emname":"xess"}'`)
    ** Created required queues (e.g. `NameOfQueue`) via e.g. link:https://help.sap.com/viewer/bf82e6b26456494cbdd197057c09979f/Cloud/en-US/97a0b3c0067044fcba0df174b9c38f5b.html[Dashboard UI]

=== Recommended

  * Installed IDE of choice (e.g. link:https://code.visualstudio.com/[Visual Studio] with installed link:https://marketplace.visualstudio.com/items?itemName=redhat.java[Java language support] plugin)

== Steps to Start

  . Check all _Prerequisites_ fulfilled (see section _Prerequisites_ above)
  . Clone the repository via `git clone https://github.com/SAP/enterprise-messaging-client-java-samples`
  . Change to project dir (`cd ./emjapi-samples-jms-sapcp`) and build with maven (`mvn install`)
  . Optional: Push to Cloud Foundry via `cf push` (*recommended to adopt the default `manifest.yml` accordingly*)

== JMS Extension

=== Additional Maven Dependencies
To use the JMS extension the following additional dependencies are necessary:

```xml
<!-- Messaging Client JMS extension for SAP CP -->
<dependency>
  <groupId>com.sap.cloud.servicesdk.xbem</groupId>
  <artifactId>emjapi-extension-sap-cp-jms</artifactId>
  <version>${version.emjapi}</version>
</dependency>
<!-- JMS API -->
<dependency>
  <groupId>javax.jms</groupId>
  <artifactId>javax.jms-api</artifactId>
  <version>2.0</version>
</dependency>
```

=== Code Snippets
To keep the code snippets small and readable the exception handling (`try/catch`) blocks have been omitted.

==== Initial JMS Connection
```java
// use Spring Cloud Foundry tools to get...
final Cloud cloud = new CloudFactory().getCloud();
// ... the MessagingService of the `Messaging Client Java API` via the ServiceConnector 
MessagingService messagingService = cloud.getSingletonServiceConnector(MessagingService.class, null);
// create JMS connection
Connection connection = messagingService.configure(ConnectionFactory.class).createConnection();
```

==== Receive from Queue
```java
// all JMS related
ConnectionFactory factory = messagingService.configure(javax.jms.ConnectionFactory.class);
Connection connection = factory.createConnection();
connection.start();
Session session = connection.createSession(false, Session.AUTO_ACKNOWLEDGE);

Queue queue = session.createQueue("queue:name-of-queue");
MessageConsumer consumer = session.createConsumer(queue);
```

==== Send to Endpoint
```java
// below here all JMS related
ConnectionFactory factory = messagingService.configure(javax.jms.ConnectionFactory.class);
Connection connection = factory.createConnection();
Session session = connection.createSession(false, Session.AUTO_ACKNOWLEDGE);
Session s = grantConnection().createSession();
TextMessage message = s.createTextMessage(event.toScsv());
MessageProducer producer = grantProducer(s, OUT_QUEUE);
producer.send(message);
```

=== Demo Flow for sample application
By default the input queue (`EmSampleInQueue`) for receiving messages and the output queue (`EmSampleOutQueue`) for send messages are separated. +
Hence messages which are sent via this application will not be received by this application. +
The recommended way to send/receive messages from this application is to use the `emjapi-samples-basic` project as described in the _Preparations for `emjapi-samples-basic`_ section.

==== Preparations for `emjapi-samples-basic`

  . All _Prerequisites_ fulfilled (see section _Project Setup_ -> _Prerequisites_ below)
  . Change into project directory of `emjapi-samples-basic`
  . Create a credentials file (e.g. `creds-sapcp.json`) with the credentials of this `emjapi-samples-jms-sapcp`
    .. Prerequisites that this `emjapi-samples-jms-sapcp` application is already deployed (`cf push`) to the SAP CP
    .. Get the credentials via `cf env emjapi-samples-jms-sapcp` (i.e. the app name as specified in the `manifest.yml`) and copy the content of the `"enterprise-messaging"` json part in the `creds-sapcp.json` (without the array `[]`; see as example `emjapi-samples-basic/src/resources/credentials.json`).
  . Build the project via maven (just `mvn` to use the correct default goal).
  . Send messages via `java -jar target/emjapi-samples-basic.jar send EmSampleInQueue creds-sapcp.json`
  . Receive messages via `java -jar target/emjapi-samples-basic.jar receive EmSampleOutQueue creds-sapcp.json`

==== Start Receive for Messages
.Endpoints
  * Request `/messages` to receive enriched messages.

.Requests
  * Sample curl: `curl https://<app-base-url>/messages` +
  (e.g. -> `curl https://xbem-emjapi-sample.cfapps.<region>.hana.ondemand.com/messages`)
  * Sample httpie: `http -S https://<app-base-url>/messages --timeout 300` +
  (e.g. -> `http -S https://xbem-emjapi-sample.cfapps.<region>.hana.ondemand.com/messages --timeout 300`)

==== Received Messages
The sample has a link:https://<app-base-url>/index.html[overview page] to get a list of the already received messages.

==== Send a Message
To send a message do a POST request at `/messages` with `text/plain` as content type and the message to be sent as body.

A sample POST request for `curl` (and a deployed sample application) look like:
```bash
curl -X POST -H "Content-Type: text/plain" -H "Cache-Control: no-cache" -d 'body_as_message_content' "https://<app-base-url>/messages"
```
.Sample POST Request with _httpie_
```
http POST https://<app-base-url>/messages body_as_message_content Content-Type:text/plain
```

==== Close Receiver
To close the connection to a receiver (receiving queue/topic endpoint) do a DELETE request at `/messages`.

A sample POST request for `curl` (and a deployed sample application) look like:
```bash
curl -X DELETE "https://<app-base-url>/messages"
```

== Support
This project is _'as-is'_ with no support, no changes being made. +
You are welcome to make changes to improve it but we are not available for questions or support of any kind.

== License
Copyright (c) 2017 SAP SE or an SAP affiliate company. All rights reserved.
This file is licensed under the _SAP SAMPLE CODE LICENSE AGREEMENT, v1.0-071618_ except as noted otherwise in the link:../LICENSE.txt[LICENSE file].