= SAP Enterprise Messaging JMS: Apache Qpid

Sample application (plain Java) of how to use the Apache Qpid JMS client to send and receive messages via SAP Cloud Platorm Enterprise Messaging. +
Tested _Messaging Client_ in version `1.7.2` (including _Apache Qpid JMS_ in version `0.32.0`) against SAP Cloud Platform Enterprise Messaging.

== JMS Extension

.Additional Maven Dependencies
```
<!-- Messaging Client JMS extension for SAP CP -->
<dependency>
  <groupId>com.sap.cloud.servicesdk.xbem</groupId>
  <artifactId>emjapi-extension-sap-cp-jms</artifactId>
  <version>${version.emjapi}</version>
</dependency>
<!-- JMS API -->
<dependency>
  <groupId>javax.jms</groupId>
  <artifactId>javax.jms-api</artifactId>
  <version>2.0</version>
</dependency>
```

.Necessary Code Snippet to Get JMS Connection Factory Configured by Messaging Service (local)
```
// create somehow the Messaging Service
MessagingService messagingService = MessagingService.with(...)
  .addSetting(MessagingService.Setting.MESSAGING_CONTEXT_IMPLEMENTATION.withValue("extension"))
  .create();
// do the extension configuration request
ConnectionFactory factory = messagingService.configure(javax.jms.ConnectionFactory.class);
```

.Sample with Initialisation of Messaging Service (local)
```
MessagingService messagingService = MessagingService.with(
    MessagingEnvironment.fromJson("{ ... }").build())
  .addSetting(MessagingService.Setting.MESSAGING_CONTEXT_IMPLEMENTATION.withValue("extension"))
  .create();

// below here all JMS-related
ConnectionFactory factory = messagingService.configure(javax.jms.ConnectionFactory.class);
Connection connection = factory.createConnection();
connection.start();
Session session = connection.createSession(false, Session.AUTO_ACKNOWLEDGE);

Queue queue = session.createQueue("queue:name-of-queue");
MessageConsumer consumer = session.createConsumer(queue);
```

== Project Setup

=== Prerequisites: Local Setup

  * Installed _Java 8_ -> link:https://java.com/de/download/[Java download]
  * Installed _Git_ -> link:https://git-scm.com/downloads[Git download]
  * Installed _Maven 3.x_ -> link:https://maven.apache.org/download.cgi[Maven download]
  * _SAP CP_ Account with _Enterprise Messaging Service_ available
    ** Optional: Installed _CloudFoundry CLI_ -> link:https://docs.cloudfoundry.org/cf-cli/install-go-cli.html[Installing the cf CLI] 
    *** This must be also fully configured with corresponding Cloud Foundry landscape to be able to do a `cf push`.


.Recommended

  * Installed IDE of choice (e.g. link:https://code.visualstudio.com/[Visual Studio Code] with installed link:https://marketplace.visualstudio.com/items?itemName=redhat.java[Java language support] plugin)

=== Prerequisites: SAP Cloud Platform

    . Created Enterprise Messaging Instance (e.g. via cli: `cf cs enterprise-messaging dev emjapi-samples-jms-basic -c '{"emname":"xess"}'`)
    . Credentials (via `create-service-key``) +
      The credentials are created during binding of an application to an _Enterprise Messaging Service Instance_ or via creation of a _service key_ for an _Enterprise Messaging Service Instance_. +      
      For creation of a _service key_ the _CloudFoundry CLI_ can be used via: `cf csk enterprise-messaging-service-instance-name key-name -c '{"emname":"sample_application"}'`. +
      After creation the _service key_ can be shown via: `cf service-key enterprise-messaging-service-instance-name key-name` +
      The content shown looks like (all `<>` enclosed values are generated for each _account/space/app_):
+
```json
{
  "messaging": [
    {
      "protocol": [
        "amqp10ws"
      ],
      "broker": {
        "type": "sapmgw",
        "version": "1.0.0"
      },
      "oa2": {
        "clientid": "<sb-clone-xbem-service-broker-space5937420a844651aee627fc1a8cd11e-clone!b298|xbem-service-broker-space!b298>",
        "clientsecret": "<PrwpcNX8cmi/BOtgQNRX7LbfOzg=>",
        "tokenendpoint": "<https://emjapi-samples-jms-basic.cfapps.<region>.hana.ondemand.com/oauth/token>"
      },
      "uri": "<wss://emjapi-samples-jms-basic.cfapps.<region>.hana.ondemand.com/protocols/amqp10ws>"
    }
  ],
  "version": "1.0",
  "xsappname": "<clone-xbem-service-broker-space5937420a844651aee627fc1a8cd11e-clone!b298|xbem-service-broker-space!b298>",
  "serviceinstanceid": "<7e474112-affe-4cbb-992a-2492a2ca7259>"
}
``` 
+
And must be provided as `resources/credentials.json` to be used for the samples. +
The name of the credentials file can be set in the `resources/em-connection.properties` as follows:
+
```
xbem.credential=credentials.json
```
  . Create a queue on the SAP CP Enterprise Messaging Instance which was created before and add the _queue name_
  in the `resources/em-connection.properties` as
+
```
xbem.jms.queue.name=<created_queue_name>
```
  . Optional (for topic sample): Create a _Queue Subscription_ on the SAP CP Enterprise Messaging Instance which was created before and add the
  _queue subscription_ as _topic name_ in the `resources/em-connection.properties` as
+
```
xbem.jms.topic.name=<created_topic_name>
```


=== Steps to Start

  . Clone the repository via `git clone https://github.com/SAP/enterprise-messaging-client-java-samples`
  . Fulfill all prerequisites (_local, SAP CP_).
  ** This includes adding mandatory settings to `em-connection.properties` (or creation of own properties file with corresponding settings)
  . Change to project dir (`cd ./emjapi-samples-jms-basic`) and build with maven (`mvn`)
  . Run sample application either via:
  ** Main method in `com.sap.xbem.sample.jms.qpid.Application`
  ** Executable jar: `java -jar target/emjapi-samples-jms-basic` (optional parameter: filename of used properties
      e.g. `java -jar target/emjapi-samples-jms-basic my-connection.properties` and sample case `RECEIVE`, `SEND`, `SEND_TOPIC` or `FULL`).
      e.g. `java -jar target/emjapi-samples-jms-basic my-connection.properties FULL`
  ** Test in `com.sap.xbem.sample.jms.qpid.ApplicationTest`


== Further Links
  * link:https://help.sap.com/viewer/product/SAP_ENTERPRISE_MESSAGING/Cloud/en-US[SAP CP Enterprise Messaging]
  * link:https://qpid.apache.org/components/jms/index.html[Qpid JMS project page]
  * link:https://qpid.apache.org/releases/qpid-jms-0.32.0/docs/index.html[Qpid JMS Documentation]
  * link:https://github.com/apache/qpid-jms/tree/0.32.0/qpid-jms-docs[Qpid JMS Documentation (github)]
  * link:https://github.com/apache/qpid-jms[Qpid JMS Sample]
  * link:https://solacesamples.github.io/solace-samples-amqp-qpid-jms2/[Solace Support for JMS over AMQP]


== License
Copyright (c) 2017 SAP SE or an SAP affiliate company. All rights reserved.
This file is licensed under the _SAP SAMPLE CODE LICENSE AGREEMENT, v1.0-071618_ except as noted otherwise in the link:../LICENSE.txt[LICENSE file].