= SAP CP Application for Enterprise Messaging

Sample Application for Enterprise Messaging based on Spring Web running on SAP Cloud Platform (@ CloudFoundry (with Enterprise Messaging Service)).

== Basic Messaging

=== Code snippets
To keep the code snippets small and readable the exception handling (`try/catch`) blocks are omitted.

==== Initial connection to binding
```java
// use Spring CloudFoundry tools to get...
final Cloud cloud = new CloudFactory().getCloud();
// ... the MessagingService of the `Messaging Client Java API` via the ServiceConnector 
MessagingService messagingService = cloud.getSingletonServiceConnector(MessagingService.class, null);
// bind to binding with name 'input' and build the MessagingEndpoint
MessagingEndpoint messagingEndpoint = messagingService.bind("input").build();
```

==== Receive from Endpoint
```java
// open stream via `receive` and define flow for each received message in `Consumer` function
inQueue.receive("client::xbem::samples::sapcp", (stream) -> {   // (1)
  stream.peek((m) -> LOG.info("Message received..."))           // (2)
    .map(Message::getContent).map(MessageEvent::new)            // (3)
    .forEach(messageEvents::add);                               // (4) 
```

  * (1): Open connection and start receiving 
  * (2): Use 'peek' method to log if a messages is received (_optional_)
  * (3): Map the received message into a `MessageEvent` (first get content, second create `MessageEvent`)
  * (4): Each received message gets added to the list of received `MessageEvents` (global field `messageEvents`)


==== Send to Endpoint
```java
messagingEndpoint.createMessage()
    .setContent("message".getBytes(StandardCharsets.UTF_8))
    .send();
```


==== Initial connection to binding with (optional) config
```java
// use Spring CloudFoundry tools to get...
final Cloud cloud = new CloudFactory().getCloud();
// ... with optional settings...
ServiceConnectorConfig config = MessagingServiceInfoProperties.init().finish();
// ... the MessagingService of the `Messaging Client Java API` via the ServiceConnector 
MessagingService messagingService = cloud.getSingletonServiceConnector(MessagingService.class, config);
// bind to binding with name 'input' and build the MessagingEndpoint
MessagingEndpoint messagingEndpoint = messagingService.bind("in_queue").build();
```

=== Demo Flow for sample application
By default the input queue (`EmSampleInQueue`) for receiving messages and the output queue (`EmSampleOutQueue`) for send messages are separated. +
Hence messages which are send via this application will not be received by this application. +
The recommended way to send/receive messages from this application is to use the `emjapi-samples-basic` project as described in the _Preparations for `emjapi-samples-basic`_ section.

==== Preparations for `emjapi-samples-basic`

  . All _Prerequisites_ fulfilled (see section _Project Setup_ -> _Prerequisites_ below)
  . Change into project directory of `emjapi-samples-basic`
  . Create a credentials file (e.g. `creds-sapcp.json`) with the credentials of this `emjapi-samples-sapcp`
    .. Prerequisites that this `emjapi-samples-sapcp` application is already deployed (`cf push`) to the SAP CP
    .. Get the credentials via `cf env emjapi-samples-sapcp` (i.e. the app name as specified in the `manifest.yml`) and copy the content of the `"enterprise-messaging"` json part in the `creds-sapcp.json` (without the array `[]`; see as example `emjapi-samples-basic/src/resources/credentials.json`).
  . Build the project via maven (just `mvn` to use the correct default goal).
  . Send messages via `java -jar target/emjapi-samples-basic.jar send EmSampleInQueue creds-sapcp.json`
  . Receive messages via `java -jar target/emjapi-samples-basic.jar receive EmSampleOutQueue creds-sapcp.json`

==== Start receive for messages
.Endpoints
  * Request `/messages` to receive enriched messages.

.Requests
  * Sample curl: `curl https://<app-base-url>/messages` +
  (e.g. -> `curl https://xbem-emjapi-sample.cfapps.<region>.hana.ondemand.com/messages`)
  * Sample httpie: `http -S https://<app-base-url>/messages --timeout 300` +
  (e.g. -> `http -S https://xbem-emjapi-sample.cfapps.<region>.hana.ondemand.com/messages --timeout 300`)

==== Received Messages
The sample has a link:https://<app-base-url>/index.html[overview page] to get a list of the already received messages.

==== Send a message
To send a message do a POST request at `/messages` with `text/plain` as content type and the to be send message as body.

A sample POST request for `curl` (and a deployed sample application) look like:
```bash
curl -X POST -H "Content-Type: text/plain" -H "Cache-Control: no-cache" -d 'body_as_message_content' "https://<app-base-url>/messages"
```
.Sample POST request with _httpie_
```
http POST https://<app-base-url>/messages body_as_message_content Content-Type:text/plain
```

==== Close Receiver
To close the connection to a receiver (receiving queue/topic endpoint) do a DELETE request at `/messages`.

A sample POST request for `curl` (and a deployed sample application) look like:
```bash
curl -X DELETE "https://<app-base-url>/messages"
```


== Project Setup

=== Prerequisites

  * Installed _Java 8_ -> link:https://java.com/de/download/[Java download]
  * Installed _Git_ -> link:https://git-scm.com/downloads[Git download]
  * Installed _Maven 3.x_ -> link:https://maven.apache.org/download.cgi[Maven download]
  * _SAP CP_ Account with _Enterprise Messaging Service_ available
    ** Optional: Installed _CloudFoundry CLI_ -> link:https://docs.cloudfoundry.org/cf-cli/install-go-cli.html[Installing the cf CLI] 
    *** This must be also fully configured with corresponding Cloud Foundry landscape to be able to do a `cf push`.
    ** Created Enterprise Messaging Instance (e.g. via cli: `cf cs enterprise-messaging dev emjapi-samples-sapcp -c '{"emname":"xess"}'`)
    ** Created required queues (`EmSampleInQueue`; `EmSampleOutQueue`) via e.g. link:https://help.sap.com/viewer/bf82e6b26456494cbdd197057c09979f/Cloud/en-US/97a0b3c0067044fcba0df174b9c38f5b.html[Dashboard UI]

=== Recommended

  * Installed IDE of choice (e.g. link:https://code.visualstudio.com/[Visual Studio] with installed link:https://marketplace.visualstudio.com/items?itemName=redhat.java[Java language support] plugin)

=== Steps to Start

  . Clone the repository via `git clone https://github.com/SAP/enterprise-messaging-client-java-samples`
  . Change to project dir (`cd ./xbem-emjapi-java-samples-jms-sapcp`) and build with maven (`mvn install`)
  . Optional: Push to Cloud Foundry via `cf push` (*recommended to adopt the default `manifest.yml` accordingly*)


== License
Copyright (c) 2017 SAP SE or an SAP affiliate company. All rights reserved.
This file is licensed under the _SAP SAMPLE CODE LICENSE AGREEMENT, v1.0-071618_ except as noted otherwise in the link:../LICENSE.txt[LICENSE file].